apiVersion: apps/v1
kind: Deployment
metadata:
  # 강의 자료의 규칙처럼 본인의 학번이나 식별자로 이름을 지정합니다. (예: sk1234-deploy)
  name: sk3003-deploy
  namespace: skala3-ai1 # 지정해주신 네임스페이스
  labels:
    app: sk3003-app
spec:
  replicas: 1 # 띄울 Pod의 개수
  selector:
    matchLabels:
      app: sk3003-app
  template:
    metadata:
      labels:
        app: sk3003-app
    spec:
      containers:
      - name: sk3003-container
        # 1단계에서 준비한 Harbor Registry 이미지 주소를 여기에 넣습니다.
        image: amdp-registry.skala-ai.com/skala26a-ai1/3003@sha256:7f5e268e184944aa7ab3fcd6c6caf73708f4fe20b86402e69b6526c3dae60604
        ports:
        - containerPort: 8080 # 애플리케이션이 바라보고 있는 포트 번호 (필요시 수정)
        # 1. 컨테이너 내부의 어느 경로에 스토리지를 연결할지 설정합니다.
        volumeMounts:
        - name: sk3003-storage
          mountPath: /app/data
      # 2. 어떤 PVC를 가져와서 쓸지 명시합니다. (containers와 같은 세로선에 맞춥니다)
      volumes:
      - name: sk3003-storage
        persistentVolumeClaim:
          claimName: sk3003-pvc